<a href="https://colab.research.google.com/github/HromovAndrey/II_mood_2_laba/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [2]:
import numpy as np
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [12]:
df
num_rows, num_colums = df.shape
print(num_rows)
print(num_colums)
df.columns
df.dtypes
df.isnull().sum()

891
7

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
dtype: int64

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [16]:
df
df[df['embarked'] == 'Q']

     pclass     sex   age  sibsp  parch     fare embarked
5         3    male   NaN      0      0   8.4583        Q
16        3    male   2.0      4      1  29.1250        Q
22        3  female  15.0      0      0   8.0292        Q
28        3  female   NaN      0      0   7.8792        Q
32        3  female   NaN      0      0   7.7500        Q
..      ...     ...   ...    ...    ...      ...      ...
790       3    male   NaN      0      0   7.7500        Q
825       3    male   NaN      0      0   6.9500        Q
828       3    male   NaN      0      0   7.7500        Q
885       3  female  39.0      0      5  29.1250        Q
890       3    male  32.0      0      0   7.7500        Q

[77 rows x 7 columns]

In [17]:

a = df[df['embarked'] == 'Q']
d = a.shape[0]
print(d)

77

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [20]:
df[df['pclass'] == 1]

     pclass     sex   age  sibsp  parch     fare embarked
1         1  female  38.0      1      0  71.2833        C
3         1  female  35.0      1      0  53.1000        S
6         1    male  54.0      0      0  51.8625        S
11        1  female  58.0      0      0  26.5500        S
23        1    male  28.0      0      0  35.5000        S
..      ...     ...   ...    ...    ...      ...      ...
871       1  female  47.0      1      1  52.5542        S
872       1    male  33.0      0      0   5.0000        S
879       1  female  56.0      0      1  83.1583        C
887       1  female  19.0      0      0  30.0000        S
889       1    male  26.0      0      0  30.0000        C

[216 rows x 7 columns]

In [21]:
first_class_passengers = df[df['pclass'] == 1]
selected_colums = first_class_passengers[['sex', 'age', 'fare']]
print(selected_colums)

        sex   age     fare
1    female  38.0  71.2833
3    female  35.0  53.1000
6      male  54.0  51.8625
11   female  58.0  26.5500
23     male  28.0  35.5000
..      ...   ...      ...
871  female  47.0  52.5542
872    male  33.0   5.0000
879  female  56.0  83.1583
887  female  19.0  30.0000
889    male  26.0  30.0000

[216 rows x 3 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками